#!/usr/bin/env python3
"""Refresh the copy of the platform contract this plugin checks itself against.

Every fact the 2026-10-02 audit found stale had the same history: Core
changed, and nothing here noticed, because nothing here held a copy of what
Core says. `templates/manifest_v2.schema.json` and
`templates/platform-contract.json` are that copy. `check_app.py` reads them
instead of keeping its own lists, and `scripts/check_repo.py` holds the
documents to them. This script is how they are refreshed: from a Manaurum
monorepo checkout, at a ref you name, read-only (`git show`, no checkout).

    python scripts/sync_contract.py --monorepo ../Manaurum [--ref origin/main]

Run `git -C <monorepo> fetch origin main` first. Then run `check_repo.py`:
whatever it now reports is a document that disagrees with the platform.

Standard library only. It is never run in CI - CI has no monorepo - which is
why its output is committed and carries the SHA it came from.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_OUT = ROOT / "templates" / "manifest_v2.schema.json"
CONTRACT_OUT = ROOT / "templates" / "platform-contract.json"

SCHEMA_SRC = "backend/app/services/_schemas/manifest_v2.schema.json"
CAPABILITIES_DIR = "backend/app/services/capabilities/"
RESERVED_SRC = "backend/app/services/v2_apps/reserved_slugs.py"
SLUG_SRC = "backend/app/services/v2_apps/traefik_yaml.py"
VALIDATOR_SRC = "backend/app/services/manifest_v2_validator.py"
TOOLS_SRC = "backend/app/agent/sdk_capability_tools.py"


def git(monorepo: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(monorepo), *args], check=True,
                          capture_output=True, text=True, encoding="utf-8").stdout


def show(monorepo: Path, ref: str, path: str) -> str:
    return git(monorepo, "show", "%s:%s" % (ref, path))


def capability_names(monorepo: Path, ref: str) -> list:
    out = git(monorepo, "grep", "-h", "-o", r'name="os\.[a-z_.]*"', ref, "--",
              CAPABILITIES_DIR)
    names = sorted({line.split('"')[1] for line in out.splitlines() if '"' in line})
    if len(names) < 20:
        raise SystemExit("found only %d capability registrations - the layout "
                         "changed; fix capability_names()" % len(names))
    return names


def reserved_slugs(text: str) -> list:
    block = re.search(r"RESERVED_SLUGS[^=]*=\s*frozenset\(\{(.*?)\}\)", text, re.S)
    if not block:
        raise SystemExit("RESERVED_SLUGS not found in %s" % RESERVED_SRC)
    return sorted(set(re.findall(r'"([a-z0-9-]+)"', block.group(1))))


def slug_pattern(text: str) -> str:
    match = re.search(r"_VALID_SLUG_RE\s*=\s*re\.compile\(r\"([^\"]+)\"\)", text)
    if not match:
        raise SystemExit("_VALID_SLUG_RE not found in %s" % SLUG_SRC)
    return match.group(1)


def write_verbs(text: str) -> list:
    block = re.search(r"_WRITE_VERB_PREFIXES\s*=\s*\((.*?)\)", text, re.S)
    if not block:
        raise SystemExit("_WRITE_VERB_PREFIXES not found in %s" % VALIDATOR_SRC)
    return sorted(set(re.findall(r'"([a-z_]+)"', block.group(1))))


def tool_name_prefix(text: str) -> str:
    # The Assistant names a hosted app's tool `sdk__<slug>__<name>`.
    match = re.search(r'f"(sdk__)\{', text)
    if not match:
        raise SystemExit("the sdk__ tool-name format was not found in %s" % TOOLS_SRC)
    return match.group(1)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--monorepo", required=True, type=Path)
    parser.add_argument("--ref", default="origin/main")
    args = parser.parse_args()

    sha = git(args.monorepo, "rev-parse", args.ref).strip()
    date = git(args.monorepo, "show", "-s", "--format=%cs", args.ref).strip()
    schema_text = show(args.monorepo, args.ref, SCHEMA_SRC)
    json.loads(schema_text)                       # refuse to vendor a broken file

    contract = {
        "_comment": "Generated by scripts/sync_contract.py from the Manaurum monorepo. "
                    "Do not edit by hand; re-run the script.",
        "source": {"ref": args.ref, "sha": sha, "date": date},
        "capabilities": capability_names(args.monorepo, args.ref),
        "reserved_slugs": reserved_slugs(show(args.monorepo, args.ref, RESERVED_SRC)),
        "slug_pattern": slug_pattern(show(args.monorepo, args.ref, SLUG_SRC)),
        "write_verb_prefixes": write_verbs(show(args.monorepo, args.ref, VALIDATOR_SRC)),
        "agent_tool": {
            "prefix": tool_name_prefix(show(args.monorepo, args.ref, TOOLS_SRC)),
            "separator": "__",
            "max_length": 64,
        },
    }

    SCHEMA_OUT.write_text(schema_text, encoding="utf-8", newline="\n")
    CONTRACT_OUT.write_text(json.dumps(contract, indent=2) + "\n", encoding="utf-8",
                            newline="\n")
    print("wrote %s and %s from %s @ %s (%s): %d capabilities"
          % (SCHEMA_OUT.relative_to(ROOT).as_posix(),
             CONTRACT_OUT.relative_to(ROOT).as_posix(), args.ref, sha[:9], date,
             len(contract["capabilities"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
